<<<<<<< HEAD
spring.application.name=test
#spring.datasource.url=jdbc:postgresql://localhost:5432/otaapp
#spring.datasource.username=ota_app
spring.application.name=travi-ota
server.port=${SERVER_PORT:8080}
# Template: spring.datasource.url=jdbc:postgressl://localhost:5432/{databaseName}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/default}
spring.datasource.username=${DB_USERNAME:traviota}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret & Expiration
app.jwt.secret=${JWT_SECRET0}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS}
app.jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION_MS:604800000}

# Connection Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000

spring.jackson.time-zone=Asia/Ho_Chi_Minh
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.default-property-inclusion=non_null

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

spring.flyway.enabled=false
>>>>>>> d105303 (New commit for Spring Security, setup env)
